bugfix: cad/cura remove NoKeyringError from import
py-keyring is stacked at 18.0.1 at the moment. cura expects 23.0.1,
which has NoKeyringError. until 23.0.1 is available again, remove it.

ImportError: cannot import name 'NoKeyringError' from 'keyring.errors'
(/usr/local/lib/python3.8/site-packages/keyring/errors.py)

https://www.freshports.org/security/py-keyring/